PierresTreats/Models/Treat.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace PierresTreats.Models
{
  public class Treat
  {
    public int TreatId { get; set; }
    [Required(ErrorMessage = "The Treat name field cannot be empty!")]
    public string Name { get; set; }
    public virtual ApplicationUser User { get; set; }
    public virtual List<FlavorTreat> JoinEntities { get; }
  }
}

PierresTreats/Controllers/TreatsController.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using System.Threading.Tasks;
using System.Security.Claims;
using PierresTreats.Models;

namespace PierresTreats.Controllers
{
  [Authorize]
  public class TreatsController : Controller
  {
    private readonly PierresTreatsContext _db;
    private readonly UserManager<ApplicationUser> _userManager;

    public TreatsController(UserManager<ApplicationUser> userManager, PierresTreatsContext db)
    {
      _userManager = userManager;
      _db = db;
    }

    [AllowAnonymous]
    public ActionResult Index()
    {
      return View(_db.Treats.ToList());
    }

    public ActionResult Create()
    {
      ViewBag.FlavorId = new SelectList(_db.Flavors, "FlavorId", "Description");
      return View();
    }

    [HttpPost]
    [HttpPost]
    public ActionResult Create(Treat treat)
    {
      if (!ModelState.IsValid)
      {
        return View(treat);
      }
      else
      {
        _db.Treats.Add(treat);
        _db.SaveChanges();
        return RedirectToAction("Index");
      }
    }

    [AllowAnonymous]
    public ActionResult Details(int id)
    {
      ViewBag.Flavors = _db.Flavors.ToList();
      Treat thisTreat = _db.Treats
        .Include(treat => treat.JoinEntities)
        .ThenInclude(join => join.Flavor)
        .FirstOrDefault(treat => treat.TreatId == id);
      return View(thisTreat);
    }

    public ActionResult Edit(int id)
    {
      Treat thisTreat = _db.Treats.FirstOrDefault(treat => treat.TreatId == id);
      return View(thisTreat);
    }

    [HttpPost]
    public ActionResult Edit(Treat treat)
    {
      _db.Entry(treat).State = EntityState.Modified;
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Delete(int id)
    {
      Treat thisTreat = _db.Treats.FirstOrDefault(treat => treat.TreatId == id);
      return View(thisTreat);
    }

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      Treat thisTreat = _db.Treats.FirstOrDefault(treat => treat.TreatId == id);
      _db.Treats.Remove(thisTreat);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult AddFlavor(int id)
    {
      Treat thisTreat = _db.Treats.FirstOrDefault(treat => treat.TreatId == id);
      ViewBag.FlavorId = new SelectList(_db.Flavors, "FlavorId", "Description");
      return View(thisTreat);
    }

    [HttpPost]
    public ActionResult AddFlavor(Treat treat, int flavorId)
    {
#nullable enable
      FlavorTreat? joinEntity = _db.FlavorTreat.FirstOrDefault(join => (join.FlavorId == flavorId && join.TreatId == treat.TreatId));
#nullable disable
      if (joinEntity == null && flavorId != 0)
      {
        _db.FlavorTreat.Add(new FlavorTreat() { FlavorId = flavorId, TreatId = treat.TreatId });
        _db.SaveChanges();
      }
      return RedirectToAction("Details", new { id = treat.TreatId });
    }

    [HttpPost]
    public ActionResult DeleteFlavor(int joinId)
    {
      FlavorTreat joinEntry = _db.FlavorTreat.FirstOrDefault(entry => entry.FlavorTreatId == joinId);
      _db.FlavorTreat.Remove(joinEntry);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }
  }
}

PierresTreats/Views/Treats/AddFlavor.cshtml
@{
  Layout = "_Layout";
}

@model PierresTreats.Models.Treat;

<h2>Add a flavor</h2>
<h4>Add a flavor to @Html.DisplayFor(model => model.Name)</h4>

@using (Html.BeginForm())
{
  @Html.HiddenFor(model => model.TreatId)

  @Html.Label("Select Flavor")
  @Html.DropDownList("FlavorId")

  <input type="submit" value="Save" />
}

PierresTreats/Views/Treats/Create.cshtml
@{
  Layout = "_Layout";
}

@model PierresTreats.Models.Treat;

<h3>Add a new treat</h3>

<p>@Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger", @style = "font-weight: 600;" })</p>

@using (Html.BeginForm())
{
  @Html.LabelFor(model => model.Name)
  @Html.TextBoxFor(model => model.Name)

  <br>
  
  <input type="submit" value="Add new treat" />
}

PierresTreats/Views/Treats/Delete.cshtml
@{
  Layout = "_Layout";
}

@model PierresTreats.Models.Treat;

<h2>Delete this treat?</h2>
<h3>@Html.DisplayNameFor(model => model.Name): @Html.DisplayFor(model => model.Name)</h3>

@using (Html.BeginForm())
{
  <input type="submit" value="Delete" />
}

PierresTreats/Views/Treats/Details.cshtml
@{
  Layout = "_Layout";
}

@model PierresTreats.Models.Treat;

<h2>Treat Details</h2>

<h3>@Html.DisplayNameFor(model => model.Name): @Html.DisplayFor(model => model.Name)</h3>

<h4>Flavors in this treat:</h4>

@if (Model.JoinEntities.Count == 0)
{
  <p>There are no flavors listed for this treat.</p>
}
else
{
  <ul>
    @foreach (var join in Model.JoinEntities)
    {
      <li>@join.Flavor.Description | 
        <span class="btn-group">
          @using (Html.BeginForm("DeleteFlavor", "Treats"))
          {
            @Html.Hidden("joinId", @join.FlavorTreatId)
            <input type="submit" value="Delete flavor" class="btn btn-link btn-sm" />
          }
        </span>
      </li>
    }
  </ul>
}

<h4>Treat options:</h4>

@Html.ActionLink("Add flavor", "AddFlavor", new { id = Model.TreatId })
@Html.ActionLink("Edit treat details", "Edit", new { id = Model.TreatId })
@Html.ActionLink("Delete treat", "Delete", new { id = Model.TreatId })

PierresTreats/Views/Treats/Edit.cshtml
@{
  Layout = "_Layout";
}

@model PierresTreats.Models.Treat;

<h2>Edit</h2>

<h4>Edit this treat: @Html.DisplayFor(model => model.Name)</h4>

@using (Html.BeginForm())
{
  @Html.HiddenFor(model => model.TreatId)

  @Html.LabelFor(model => model.Name)
  @Html.EditorFor(model => model.Name)
  
  <br>

  <input type="submit" value="Save" />
}

PierresTreats/Views/Treats/Index.cshtml
@{
  Layout = "_Layout";
}

@using PierresTreats.Models;
@model List<PierresTreats.Models.Treat>;

<h1>Treats</h1>
<p>Select a treat to see it's details!</p>

@if (Model.Count == 0)
{
  <p>No treats have been added yet.</p>
}

<ul>
  @foreach (Treat treat in Model)
  {
    <li>@Html.ActionLink($"{treat.Name}", "Details", new { id = treat.TreatId })</li>
  }
</ul>

@Html.ActionLink("Add treat", "Create")