PierresTreats/Models/Flavor.cs
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace PierresTreats.Models
{
  public class Flavor
  {
    public int FlavorId { get; set; }
    [Required(ErrorMessage = "The Flavor description field cannot be empty!")]
    public string Description { get; set; }
    public virtual List<FlavorTreat> JoinEntities { get; set; }
  }
}

PierresTreats/Controllers/FlavorsController.cs
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using System.Threading.Tasks;
using System.Security.Claims;
using PierresTreats.Models;

namespace PierresTreats.Controllers
{
  [Authorize]
  public class FlavorsController : Controller
  {
    private readonly PierresTreatsContext _db;
    private readonly UserManager<ApplicationUser> _userManager;

    public FlavorsController(UserManager<ApplicationUser> userManager, PierresTreatsContext db)
    {
      _userManager = userManager;
      _db = db;
    }

    [AllowAnonymous]
    public ActionResult Index()
    {
      return View(_db.Flavors.ToList());
    }

    public ActionResult Create()
    {
      return View();
    }

    [HttpPost]
    public ActionResult Create(Flavor flavor)
    {
      if (!ModelState.IsValid)
      {
        return View(flavor);
      }
      else
      {
        _db.Flavors.Add(flavor);
        _db.SaveChanges();
        return RedirectToAction("Index");
      }
    }

    [AllowAnonymous]
    public ActionResult Details(int id)
    {
      ViewBag.Treats = _db.Treats.ToList();
      Flavor thisFlavor = _db.Flavors
        .Include(flavor => flavor.JoinEntities)
        .ThenInclude(join => join.Treat)
        .FirstOrDefault(flavor => flavor.FlavorId == id);
      return View(thisFlavor);
    }

    public ActionResult Edit(int id)
    {
      Flavor thisFlavor = _db.Flavors.FirstOrDefault(flavor => flavor.FlavorId == id);
      return View(thisFlavor);
    }

    [HttpPost]
    public ActionResult Edit(Flavor flavor)
    {
      _db.Entry(flavor).State = EntityState.Modified;
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult AddTreat(int id)
    {
      Flavor thisFlavor = _db.Flavors.FirstOrDefault(flavor => flavor.FlavorId == id);
      ViewBag.TreatId = new SelectList(_db.Treats, "TreatId", "Name");
      return View(thisFlavor);
    }

    [HttpPost]
    public ActionResult AddTreat(Flavor flavor, int TreatId)
    {
      if (TreatId != 0)
      {
        _db.FlavorTreat.Add(new FlavorTreat() { TreatId = TreatId, FlavorId = flavor.FlavorId });
      }
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    public ActionResult Delete(int id)
    {
      Flavor thisFlavor = _db.Flavors.FirstOrDefault(flavor => flavor.FlavorId == id);
      return View(thisFlavor);
    }

    [HttpPost, ActionName("Delete")]
    public ActionResult DeleteConfirmed(int id)
    {
      Flavor thisFlavor = _db.Flavors.FirstOrDefault(flavor => flavor.FlavorId == id);
      _db.Flavors.Remove(thisFlavor);
      _db.SaveChanges();
      return RedirectToAction("Index");
    }

    [HttpPost]
    public ActionResult DeleteTreat(int joinId)
    {
      FlavorTreat joinEntry = _db.FlavorTreat.FirstOrDefault(entry => entry.FlavorTreatId == joinId);
      _db.FlavorTreat.Remove(joinEntry);
      _db.SaveChanges();
      return RedirectToAction("Details", new { id = joinEntry.FlavorId });
    }
  }
}

PierresTreats/Views/Flavors/AddTreat.cshtml
@{
  Layout = "_Layout";
}

@model PierresTreats.Models.Flavor;

<h2>Add a treat</h2>
<h4>Add a treat to @Html.DisplayFor(model => model.Description)</h4>

@using (Html.BeginForm())
{
  @Html.HiddenFor(model => model.FlavorId)

  @Html.Label("Select treat")
  @Html.DropDownList("TreatId")

  <input type="submit" value="Save" />
}

PierresTreats/Views/Flavors/Create.cshtml
@{
  Layout = "_Layout";
}

@model PierresTreats.Models.Flavor;

<h3>Add a new flavor</h3>

 <p>@Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger", @style = "font-weight: 600;" })
  </p>

@using (Html.BeginForm())
{
  @Html.LabelFor(model => model.Description)
  @Html.TextBoxFor(model => model.Description)

  <input type="submit" value="Add new flavor" />
}

PierresTreats/Views/Flavors/Delete.cshtml
@{
  Layout = "_Layout";
}

@model PierresTreats.Models.Flavor

<h2>Are you sure you want to delete this?</h2>

@Html.DisplayName("Flavor Name"): @Html.DisplayFor(model => model.Description)
@using (Html.BeginForm())
{
  <input type="submit" value="Delete" />
}

PierresTreats/Views/Flavors/Details.cshtml
@{
  Layout = "_Layout";
}

@model PierresTreats.Models.Flavor;

<h2>Flavor Details</h2>

<h3>@Html.DisplayNameFor(model => model.Description): @Html.DisplayFor(model => model.Description)</h3>

<h4>Treats with this flavor:</h4>

@if (Model.JoinEntities.Count == 0)
{
  <p>There are no treats with this flavor.</p>
}
else
{
  <ul>
    @foreach (var join in Model.JoinEntities)
    {
      <li>@join.Treat.Name | 
        <span class="btn-group">
          @using (Html.BeginForm("DeleteTreat", "Flavors"))
          {
            @Html.Hidden("joinId", @join.FlavorTreatId)
            <input type="submit" value="Delete Treat" class="btn btn-link btn-sm" />
          }
        </span>
      </li>
    }
  </ul>
}

<h4>Flavor options:</h4>

@Html.ActionLink("Add treat", "AddTreat", new { id = Model.FlavorId })
@Html.ActionLink("Edit flavor details", "Edit", new { id = Model.FlavorId })
@Html.ActionLink("Delete flavor", "Delete", new { id = Model.FlavorId })

PierresTreats/Views/Flavors/Edit.cshtml
@{
  Layout = "_Layout";
}

@model PierresTreats.Models.Flavor;

<h2>Edit</h2>

<h4>Edit this flavor: @Html.DisplayFor(model => model.Description)</h4>

@using (Html.BeginForm())
{
  @Html.HiddenFor(model => model.FlavorId)

  @Html.LabelFor(model => model.Description)
  @Html.EditorFor(model => model.Description)
  
  <br>

  <input type="submit" value="Save" />
}

PierresTreats/Views/Flavors/Index.cshtml
@{
  Layout = "_Layout";
}

@using PierresTreats.Models;
@model List<PierresTreats.Models.Flavor>;

<h1>Flavors</h1>
<p>Select a flavor to see it's description!</p>

@if (Model.Count == 0)
{
  <p>No flavors have been added yet.</p>
}

<ul>
  @foreach (Flavor flavor in Model)
  {
    <li>@Html.ActionLink($"{flavor.Description}", "Details", new { id = flavor.FlavorId })</li>
  }
</ul>

@Html.ActionLink("Add Flavor", "Create")